### ISSUE TITLE
Fixing dependency on fork of glossy?

### ISSUE THREAD

**Issue by antonjonsson** [myndzi/syslog-streams2#1]
Any plans to fix this?

**Comment by krisreeves-stripe** [comment]
The author of glossy seemed ideologically opposed to accepting the patch, so it wasn't on my todo list. It's been a long time, so I can check if the underlying problem is solved I suppose

**Comment by antonjonsson** [comment]
Trying to read through what was going on and seems like something may have been merged there in #34?

**Comment by krisreeves-stripe** [comment]
Looks like it finally took. I don't remember the context/problem anymore, will check it out tonight on off-hours.

**Comment by myndzi** [comment]
Unfortunately, even though some patches have been merged, a new version hasn't been published. I tried my test suite with the latest published version of glossy and it fails. You may be able to watch or +1 this issue to get notified if/when glossy does publish its latest code: https://github.com/squeeks/glossy/issues/37

**Comment by myndzi** [comment]
Is your problem with the dependency being a git repo? I could publish to a namespaced package or something if that would help you out

**Comment by antonjonsson** [comment]
Yeah that would work

**Comment by myndzi** [comment]
That should hopefully do it -- can you confirm?

**Comment by antonjonsson** [comment]
I guess I should have stated from the beginning that it's the syslog2 module we are looking to use, so would also need that one updated to use this new version of syslog-streams.

**Comment by myndzi** [comment]
It should be fine if you just re-`npm install` to get the new version of this package

**Comment by myndzi** [comment]
```
myndzi@seckzi:~/syslog2$ npm install syslog-streams2@latest
- glossy@0.1.7 node_modules/glossy
syslog2@1.0.7 /home/myndzi/syslog2
└─┬ syslog-streams2@1.0.3
  └── @myndzi/glossy@0.1.8
```

A blank `npm install` should fetch the latest compatible version too, which is `1.0.3`

**Comment by antonjonsson** [comment]
Yeah I'm stupid for some reason thought the dependency on syslog-streams2 was locked. This all works fine now, thank you very much!

**Comment by myndzi** [comment]
Glad to hear it!
